---

# - name: "install npm"
#   become: true
#   apk:
#     name: ["npm"]
#     state: latest
#     update_cache: yes

# - name: "Install pm2 if not installed"
#   command: npm install pm2 -g
#   args:
#     creates: /usr/local/bin/pm2
#   become: yes

# - name: "upgrade packages."
#   become: true
#   apk:
#     upgrade: "yes"

# - name: "install dependencies."
#   become: true
#   apk:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: extract artifact
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: .

- name: "start app"
  become: yes 
  shell: |
    npm install
    pm2 stop all
    pm2 start npm -- start
  # command: pm2 stop default
  # command: pm2 start npm -- start
# npm install
# pm2 stop default
# pm2 start npm -- start